formatter: "markdown table"

version: "0.16"

header-from: ./.terraform-docs/header.md
footer-from: ./.terraform-docs/footer.md

recursive:
  enabled: false
  path: ""

sections:
  hide: []
  show: []

  content: |-

    {{ .Header }}
  
    {{ .Providers }}
  
    {{ .Requirements }}
  
    {{ .Inputs }}
  
    {{ .Outputs }}
  
    {{ .Resources }}
  
    {{ .Footer }}
  
  output:
    file: ./README.md
    mode: inject
    template: |-
      <!-- BEGIN_TF_DOCS -->
      {{ .Content }}
      ## Copyright (c)
      > ###### Copyright (c) Deutsche Börse AG.
      > ###### Licensed under the Apache License, Version 2.0 (the "License")
      > ######
      <!-- END_TF_DOCS -->
      
  output-values:
    enabled: false
    from: ""

  sort:
    enabled: true
    by: name

  settings:
    anchor: true
    color: true
    default: true
    description: false
    escape: true
    hide-empty: false
    html: true
    indent: 2
    lockfile: true
    read-comments: true
    required: true
    sensitive: true
    type: true